version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins-data:/
    ports:
      - 8080:8080
      - 5000:5000
    # container_name: jenkins

volumes:
  jenkins-data: